export { default as reactLogo } from './react.svg';
export { default as reactRouterLogo } from './react-router.svg';
export { default as graphqlLogo } from './graphql.svg';
export { default as nodeLogo } from './nodejs.svg';
export { default as exLogo } from './express.png';
export { default as mongoLogo } from './mongodb.svg';
export { default as postgresLogo } from './postgresql.svg';
export { default as sequelizeLogo } from './sequelize.svg';
export { default as pythonLogo } from './python.svg';
export { default as djangoLogo } from './django.svg';
export { default as htmlLogo } from './html.svg';
export { default as cssLogo } from './css.svg';
export { default as jsLogo } from './js.svg';
export { default as herokuLogo } from './heroku.svg';
export { default as gitLogo } from './git.svg';
export { default as githubLogo } from './github.svg';
export { default as terminalLogo } from './terminal.svg';
export { default as vscodeLogo } from './vs-code.svg';
// export { default as javascriptLogo } from './javascript.svg';
// export { default as expressLogo } from './express-full.svg';
// export { default as mongoFullLogo } from './mongodb-full.svg';
// export { default as jsonLogo } from './json.svg';
